workflows:
  android-apk-build:
    name: Android APK Build
    instance_type: mac_mini_m1
    
  sdk: android
    
    scripts:
      - name: Build unsigned debug APK
        script: | 
          cd ./app
          ./gradlew assembleDebug
          
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
