workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      android_sdk_version: "33"
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          gradle wrapper --gradle-version 7.3.3
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
