# codemagic.yaml (Final Version with Gradle Wrapper Generation)
workflows:
  android-apk-build:
    name: Android APK Build
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
    
    scripts:
      - name: Generate Gradle Wrapper
        script: | 
          gradle wrapper --gradle-version 7.0.2
          
      - name: Build debug APK
        script: | 
          ./gradlew assembleDebug
          
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
