# codemagic.yaml (Final and Corrected Version)
workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1

    # আমরা এখানে জোর করে Java 11 ব্যবহার করতে বলছি
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home

    scripts:
      - name: Build debug APK
        script: | 
          ./gradlew assembleDebug
          
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
