# codemagic.yaml (Corrected Syntax Version)
workflows:
  android-apk-build:
    name: Android APK Build
    instance_type: mac_mini_m1
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=/Users/builder/Library/Android/sdk" > "$CM_BUILD_DIR/local.properties"
      - name: Set up gradle wrapper
        script: |
          gradle wrapper --gradle-version 7.0.2 # Use a specific gradle version
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
