# codemagic.yaml (Final Version with Correct Gradle Version)
workflows:
  android-apk-build:
    name: Android APK Build
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
    
    scripts:
      - name: Generate Gradle Wrapper
        script: | 
          # --- Shudhu ei line-ti poriborton kora hoyeche ---
          gradle wrapper --gradle-version 7.3.3
          
      - name: Build debug APK
        script: | 
          ./gradlew assembleDebug
          
      artifacts:
        - app/build/outputs/apk/debug/**/*.apk
