workflows:
  android-apk-build:
    name: Android APK Build
    instance_type: mac_mini_m1
    environment:
      android_sdk_version: '30.0.3' # Or your desired SDK version
    scripts:
      - name: Build Android APK
        script: | 
          cd ./app # Navigate to the 'app' directory if needed
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
